# Generated by Django 4.2.13 on 2025-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharenotes',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
