# Generated by Django 4.2.13 on 2025-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0002_sharenotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('amt', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
